// <auto-generated />
using FoodPickerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodPickerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309133427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoodPickerAPI.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("FoodPickerAPI.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Carbs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Protein")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 266,
                            Carbs = "33g",
                            Cuisine = "Italian",
                            Emoji = "🍕",
                            Fat = "10g",
                            Mood = "comfort,cheesy",
                            Name = "Margherita Pizza",
                            Protein = "11g"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 490,
                            Carbs = "55g",
                            Cuisine = "South Asian",
                            Emoji = "🍛",
                            Fat = "14g",
                            Mood = "hearty,spicy",
                            Name = "Chicken Biryani",
                            Protein = "28g"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 200,
                            Carbs = "38g",
                            Cuisine = "Japanese",
                            Emoji = "🍣",
                            Fat = "2g",
                            Mood = "light,fresh",
                            Name = "Sushi Rolls",
                            Protein = "9g"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 350,
                            Carbs = "28g",
                            Cuisine = "Mexican",
                            Emoji = "🌮",
                            Fat = "16g",
                            Mood = "comfort,spicy",
                            Name = "Beef Tacos",
                            Protein = "21g"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 180,
                            Carbs = "14g",
                            Cuisine = "American",
                            Emoji = "🥗",
                            Fat = "11g",
                            Mood = "light,healthy",
                            Name = "Caesar Salad",
                            Protein = "8g"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 400,
                            Carbs = "52g",
                            Cuisine = "Thai",
                            Emoji = "🍜",
                            Fat = "11g",
                            Mood = "hearty,sweet",
                            Name = "Pad Thai",
                            Protein = "20g"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 438,
                            Carbs = "12g",
                            Cuisine = "South Asian",
                            Emoji = "🍗",
                            Fat = "32g",
                            Mood = "comfort,hearty",
                            Name = "Butter Chicken",
                            Protein = "26g"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 150,
                            Carbs = "10g",
                            Cuisine = "Mediterranean",
                            Emoji = "🥙",
                            Fat = "11g",
                            Mood = "light,fresh",
                            Name = "Greek Salad",
                            Protein = "5g"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 436,
                            Carbs = "60g",
                            Cuisine = "Japanese",
                            Emoji = "🍜",
                            Fat = "12g",
                            Mood = "comfort,hearty",
                            Name = "Ramen",
                            Protein = "22g"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 535,
                            Carbs = "40g",
                            Cuisine = "American",
                            Emoji = "🍔",
                            Fat = "29g",
                            Mood = "comfort,cheesy",
                            Name = "Cheeseburger",
                            Protein = "28g"
                        },
                        new
                        {
                            Id = 11,
                            Calories = 320,
                            Carbs = "42g",
                            Cuisine = "Mediterranean",
                            Emoji = "🧆",
                            Fat = "13g",
                            Mood = "light,healthy",
                            Name = "Falafel Wrap",
                            Protein = "12g"
                        },
                        new
                        {
                            Id = 12,
                            Calories = 100,
                            Carbs = "6g",
                            Cuisine = "Thai",
                            Emoji = "🍲",
                            Fat = "3g",
                            Mood = "light,spicy",
                            Name = "Tom Yum Soup",
                            Protein = "8g"
                        },
                        new
                        {
                            Id = 13,
                            Calories = 510,
                            Carbs = "58g",
                            Cuisine = "Italian",
                            Emoji = "🍝",
                            Fat = "21g",
                            Mood = "comfort,cheesy",
                            Name = "Pasta Carbonara",
                            Protein = "22g"
                        },
                        new
                        {
                            Id = 14,
                            Calories = 595,
                            Carbs = "60g",
                            Cuisine = "British",
                            Emoji = "🐟",
                            Fat = "28g",
                            Mood = "hearty,comfort",
                            Name = "Fish & Chips",
                            Protein = "27g"
                        },
                        new
                        {
                            Id = 15,
                            Calories = 210,
                            Carbs = "40g",
                            Cuisine = "American",
                            Emoji = "🫐",
                            Fat = "6g",
                            Mood = "fresh,healthy",
                            Name = "Acai Bowl",
                            Protein = "5g"
                        });
                });

            modelBuilder.Entity("FoodPickerAPI.Models.Favourite", b =>
                {
                    b.HasOne("FoodPickerAPI.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });
#pragma warning restore 612, 618
        }
    }
}
