// <auto-generated />
using FoodPickerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodPickerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507033037_AddCuisineType")]
    partial class AddCuisineType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoodPickerAPI.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("FoodPickerAPI.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Carbs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Moods")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Protein")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TasteProfile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 360,
                            Carbs = "72g",
                            Cuisine = "Thai",
                            CuisineType = "Asian",
                            Emoji = "🥭",
                            Fat = "8g",
                            Moods = "Happy",
                            Name = "Mango Sticky Rice",
                            Protein = "5g",
                            TasteProfile = "sweet,rich,creamy"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 490,
                            Carbs = "75g",
                            Cuisine = "Korean",
                            CuisineType = "Asian",
                            Emoji = "🍚",
                            Fat = "16g",
                            Moods = "Happy",
                            Name = "Bibimbap",
                            Protein = "25g",
                            TasteProfile = "umami,bold,colourful"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 266,
                            Carbs = "33g",
                            Cuisine = "Italian",
                            CuisineType = "Global",
                            Emoji = "🍕",
                            Fat = "10g",
                            Moods = "Happy,Lazy",
                            Name = "Margherita Pizza",
                            Protein = "11g",
                            TasteProfile = "sweet,cheesy,bold"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 350,
                            Carbs = "28g",
                            Cuisine = "Mexican",
                            CuisineType = "Global",
                            Emoji = "🌮",
                            Fat = "16g",
                            Moods = "Happy",
                            Name = "Beef Tacos",
                            Protein = "21g",
                            TasteProfile = "bold,spicy,fun"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 436,
                            Carbs = "60g",
                            Cuisine = "Japanese",
                            CuisineType = "Asian",
                            Emoji = "🍜",
                            Fat = "12g",
                            Moods = "Sad,Tired",
                            Name = "Ramen",
                            Protein = "22g",
                            TasteProfile = "umami,warm,soft"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 210,
                            Carbs = "38g",
                            Cuisine = "South Asian",
                            CuisineType = "Asian",
                            Emoji = "🍲",
                            Fat = "4g",
                            Moods = "Sad,Tired",
                            Name = "Khichdi",
                            Protein = "9g",
                            TasteProfile = "mild,warm,soft"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 350,
                            Carbs = "40g",
                            Cuisine = "American",
                            CuisineType = "Global",
                            Emoji = "🧀",
                            Fat = "14g",
                            Moods = "Sad,Lazy",
                            Name = "Mac & Cheese",
                            Protein = "14g",
                            TasteProfile = "sweet,cheesy,carb-rich"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 380,
                            Carbs = "40g",
                            Cuisine = "French",
                            CuisineType = "Global",
                            Emoji = "🍫",
                            Fat = "22g",
                            Moods = "Sad,Romantic",
                            Name = "Chocolate Lava Cake",
                            Protein = "5g",
                            TasteProfile = "bittersweet,warm,rich"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 280,
                            Carbs = "54g",
                            Cuisine = "Korean",
                            CuisineType = "Asian",
                            Emoji = "🍢",
                            Fat = "4g",
                            Moods = "Stressed,Bored",
                            Name = "Tteokbokki",
                            Protein = "7g",
                            TasteProfile = "spicy,chewy,sweet"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 180,
                            Carbs = "10g",
                            Cuisine = "Thai",
                            CuisineType = "Asian",
                            Emoji = "🍲",
                            Fat = "5g",
                            Moods = "Stressed",
                            Name = "Tom Yum Soup",
                            Protein = "20g",
                            TasteProfile = "spicy,sour,warm"
                        },
                        new
                        {
                            Id = 11,
                            Calories = 480,
                            Carbs = "52g",
                            Cuisine = "Mexican",
                            CuisineType = "Global",
                            Emoji = "🧆",
                            Fat = "24g",
                            Moods = "Stressed,Bored",
                            Name = "Nachos",
                            Protein = "14g",
                            TasteProfile = "salty,crunchy,cheesy"
                        },
                        new
                        {
                            Id = 12,
                            Calories = 320,
                            Carbs = "40g",
                            Cuisine = "Middle Eastern",
                            CuisineType = "Global",
                            Emoji = "🥙",
                            Fat = "12g",
                            Moods = "Stressed",
                            Name = "Hummus & Pita",
                            Protein = "11g",
                            TasteProfile = "salty,earthy,light"
                        },
                        new
                        {
                            Id = 13,
                            Calories = 400,
                            Carbs = "48g",
                            Cuisine = "Vietnamese",
                            CuisineType = "Asian",
                            Emoji = "🍜",
                            Fat = "10g",
                            Moods = "Tired",
                            Name = "Pho",
                            Protein = "27g",
                            TasteProfile = "warm,umami,light"
                        },
                        new
                        {
                            Id = 14,
                            Calories = 438,
                            Carbs = "12g",
                            Cuisine = "South Asian",
                            CuisineType = "Asian",
                            Emoji = "🍗",
                            Fat = "32g",
                            Moods = "Tired,Sad",
                            Name = "Butter Chicken",
                            Protein = "26g",
                            TasteProfile = "warm,rich,soft"
                        },
                        new
                        {
                            Id = 15,
                            Calories = 510,
                            Carbs = "58g",
                            Cuisine = "Italian",
                            CuisineType = "Global",
                            Emoji = "🍝",
                            Fat = "21g",
                            Moods = "Tired,Lazy",
                            Name = "Pasta Carbonara",
                            Protein = "22g",
                            TasteProfile = "rich,warm,soft"
                        },
                        new
                        {
                            Id = 16,
                            Calories = 180,
                            Carbs = "20g",
                            Cuisine = "American",
                            CuisineType = "Global",
                            Emoji = "🥣",
                            Fat = "4g",
                            Moods = "Tired,Sad",
                            Name = "Chicken Noodle Soup",
                            Protein = "14g",
                            TasteProfile = "warm,mild,light"
                        },
                        new
                        {
                            Id = 17,
                            Calories = 350,
                            Carbs = "42g",
                            Cuisine = "Japanese",
                            CuisineType = "Asian",
                            Emoji = "🐙",
                            Fat = "12g",
                            Moods = "Bored",
                            Name = "Takoyaki",
                            Protein = "14g",
                            TasteProfile = "umami,savoury,fun"
                        },
                        new
                        {
                            Id = 18,
                            Calories = 490,
                            Carbs = "28g",
                            Cuisine = "Korean",
                            CuisineType = "Asian",
                            Emoji = "🍗",
                            Fat = "26g",
                            Moods = "Bored,Happy",
                            Name = "Korean Fried Chicken",
                            Protein = "30g",
                            TasteProfile = "salty,crunchy,sweet"
                        },
                        new
                        {
                            Id = 19,
                            Calories = 520,
                            Carbs = "58g",
                            Cuisine = "American",
                            CuisineType = "Global",
                            Emoji = "🍟",
                            Fat = "26g",
                            Moods = "Bored,Lazy",
                            Name = "Loaded Fries",
                            Protein = "12g",
                            TasteProfile = "salty,crunchy,cheesy"
                        },
                        new
                        {
                            Id = 20,
                            Calories = 310,
                            Carbs = "40g",
                            Cuisine = "Spanish",
                            CuisineType = "Global",
                            Emoji = "🍩",
                            Fat = "15g",
                            Moods = "Bored,Happy",
                            Name = "Churros",
                            Protein = "4g",
                            TasteProfile = "sweet,crunchy,fun"
                        },
                        new
                        {
                            Id = 21,
                            Calories = 480,
                            Carbs = "62g",
                            Cuisine = "Japanese",
                            CuisineType = "Asian",
                            Emoji = "🍣",
                            Fat = "14g",
                            Moods = "Romantic",
                            Name = "Sushi Platter",
                            Protein = "24g",
                            TasteProfile = "umami,delicate,elegant"
                        },
                        new
                        {
                            Id = 22,
                            Calories = 470,
                            Carbs = "20g",
                            Cuisine = "Chinese",
                            CuisineType = "Asian",
                            Emoji = "🦆",
                            Fat = "30g",
                            Moods = "Romantic,Hungry",
                            Name = "Peking Duck",
                            Protein = "28g",
                            TasteProfile = "rich,crispy,umami"
                        },
                        new
                        {
                            Id = 23,
                            Calories = 400,
                            Carbs = "42g",
                            Cuisine = "Italian",
                            CuisineType = "Global",
                            Emoji = "🍰",
                            Fat = "22g",
                            Moods = "Romantic,Happy",
                            Name = "Tiramisu",
                            Protein = "7g",
                            TasteProfile = "bittersweet,rich,creamy"
                        },
                        new
                        {
                            Id = 24,
                            Calories = 440,
                            Carbs = "18g",
                            Cuisine = "French",
                            CuisineType = "Global",
                            Emoji = "🥩",
                            Fat = "22g",
                            Moods = "Romantic",
                            Name = "Beef Bourguignon",
                            Protein = "32g",
                            TasteProfile = "rich,umami,hearty"
                        },
                        new
                        {
                            Id = 25,
                            Calories = 490,
                            Carbs = "55g",
                            Cuisine = "South Asian",
                            CuisineType = "Asian",
                            Emoji = "🍛",
                            Fat = "14g",
                            Moods = "Hungry",
                            Name = "Chicken Biryani",
                            Protein = "28g",
                            TasteProfile = "spicy,hearty,aromatic"
                        },
                        new
                        {
                            Id = 26,
                            Calories = 500,
                            Carbs = "48g",
                            Cuisine = "Malaysian",
                            CuisineType = "Asian",
                            Emoji = "🍱",
                            Fat = "22g",
                            Moods = "Hungry",
                            Name = "Nasi Lemak",
                            Protein = "22g",
                            TasteProfile = "rich,spicy,filling"
                        },
                        new
                        {
                            Id = 27,
                            Calories = 535,
                            Carbs = "40g",
                            Cuisine = "American",
                            CuisineType = "Global",
                            Emoji = "🍔",
                            Fat = "29g",
                            Moods = "Hungry,Bored",
                            Name = "Cheeseburger",
                            Protein = "28g",
                            TasteProfile = "savoury,rich,hearty"
                        },
                        new
                        {
                            Id = 28,
                            Calories = 450,
                            Carbs = "38g",
                            Cuisine = "Middle Eastern",
                            CuisineType = "Global",
                            Emoji = "🌯",
                            Fat = "18g",
                            Moods = "Hungry",
                            Name = "Shawarma",
                            Protein = "28g",
                            TasteProfile = "spicy,savoury,filling"
                        },
                        new
                        {
                            Id = 29,
                            Calories = 380,
                            Carbs = "52g",
                            Cuisine = "Chinese",
                            CuisineType = "Asian",
                            Emoji = "🍳",
                            Fat = "14g",
                            Moods = "Lazy,Tired",
                            Name = "Fried Rice",
                            Protein = "12g",
                            TasteProfile = "savoury,familiar,easy"
                        },
                        new
                        {
                            Id = 30,
                            Calories = 400,
                            Carbs = "52g",
                            Cuisine = "Thai",
                            CuisineType = "Asian",
                            Emoji = "🍜",
                            Fat = "11g",
                            Moods = "Lazy",
                            Name = "Pad Thai",
                            Protein = "20g",
                            TasteProfile = "sweet,savoury,familiar"
                        },
                        new
                        {
                            Id = 31,
                            Calories = 380,
                            Carbs = "30g",
                            Cuisine = "American",
                            CuisineType = "Global",
                            Emoji = "🥪",
                            Fat = "22g",
                            Moods = "Lazy,Sad",
                            Name = "Grilled Cheese Sandwich",
                            Protein = "14g",
                            TasteProfile = "cheesy,warm,simple"
                        },
                        new
                        {
                            Id = 32,
                            Calories = 220,
                            Carbs = "16g",
                            Cuisine = "Middle Eastern",
                            CuisineType = "Global",
                            Emoji = "🍳",
                            Fat = "12g",
                            Moods = "Lazy",
                            Name = "Shakshuka",
                            Protein = "12g",
                            TasteProfile = "savoury,warm,easy"
                        });
                });

            modelBuilder.Entity("FoodPickerAPI.Models.Favourite", b =>
                {
                    b.HasOne("FoodPickerAPI.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });
#pragma warning restore 612, 618
        }
    }
}
